In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('wine-quality.csv')

In [4]:
df.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [5]:
df.describe()

       fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [6]:
df['quality'].value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [7]:
X = df.drop(columns='quality', axis = 1)
Y = df['quality']

In [8]:
X.head()

   fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0            7.4              0.70         0.00  ...  3.51       0.56      9.4
1            7.8              0.88         0.00  ...  3.20       0.68      9.8
2            7.8              0.76         0.04  ...  3.26       0.65      9.8
3           11.2              0.28         0.56  ...  3.16       0.58      9.8
4            7.4              0.70         0.00  ...  3.51       0.56      9.4

[5 rows x 11 columns]

In [9]:
Y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
# X = scaler.fit_transform(X)

In [12]:
print(X)

[[-0.52835961  0.96187667 -1.39147228 ...  1.28864292 -0.57920652
  -0.96024611]
 [-0.29854743  1.96744245 -1.39147228 ... -0.7199333   0.1289504
  -0.58477711]
 [-0.29854743  1.29706527 -1.18607043 ... -0.33117661 -0.04808883
  -0.58477711]
 ...
 [-1.1603431  -0.09955388 -0.72391627 ...  0.70550789  0.54204194
   0.54162988]
 [-1.39015528  0.65462046 -0.77526673 ...  1.6773996   0.30598963
  -0.20930812]
 [-1.33270223 -1.21684919  1.02199944 ...  0.51112954  0.01092425
   0.54162988]]

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify=Y, random_state=42)

In [41]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
import numpy as np

best_mse = float("inf")

for trees in [50, 100, 200]:

    for depth in [5, 10, None]:

        model = RandomForestRegressor(
            n_estimators=trees, max_depth=depth, random_state=42
        )

        scores = cross_val_score(model, X, Y, cv=10, scoring="neg_mean_squared_error")

        mse = (-scores).mean()

        print(f"trees={trees}, depth={depth}, mse={mse:.4f}")

        if mse < best_mse:
            best_mse = mse
            best_trees = trees
            best_depth = depth

print(f"\nBest: trees={best_trees}, depth={best_depth}, mse={best_mse:.4f}")

trees=50, depth=5, mse=0.4200
trees=50, depth=10, mse=0.4227
trees=50, depth=None, mse=0.4295
trees=100, depth=5, mse=0.4182
trees=100, depth=10, mse=0.4203
trees=100, depth=None, mse=0.4251
trees=200, depth=5, mse=0.4189
trees=200, depth=10, mse=0.4223
trees=200, depth=None, mse=0.4255

Best: trees=100, depth=5, mse=0.4182

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score

model = Pipeline(
    [("scaler", StandardScaler()), ("svr", SVR(kernel="rbf", C=0.55, gamma="scale"))]
)

scores = cross_val_score(model, X, Y, cv=10, scoring="neg_mean_squared_error")

mse = (-scores).mean()

print(mse)

0.41767644163295514